name: Procress Image

on:
  workflow_dispatch:

env:
  AWS_ENDPOINT_URL: s3.ap-northeast-1.wasabisys.com
  AWS_BUCKET_NAME: assets.potapoyo.com/photo/202408/test_20240826

jobs:
  image_to_webp:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: (Actions Only) Check AWS CLI
        run: |
          aws --version

      - name: Install Dependencies Packages.
        run: |
         sudo apt-get update
         sudo apt-get -y install webp 

      - name: AWS Configure
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          aws configure list

      - name: List S3 bucket contents
        run: |
          aws s3 ls --recursive --endpoint-url https://$AWS_ENDPOINT_URL $AWS_BUCKET_NAME/

      - name: Check for .webp files in S3
        run: |
          if aws s3 ls --recursive --endpoint-url https://$AWS_ENDPOINT_URL $AWS_BUCKET_NAME/ | grep '\.webp$'; then
            echo "Error: .webp files found in the bucket"
            exit 1
          else
            echo "No .webp files found. Proceeding..."
          fi

      - name: Create Working Directory
        run: |
          pwd
          mkdir -p workdir

      - name: Download Files from S3
        run: |
          aws s3 sync --endpoint-url https://$AWS_ENDPOINT_URL s3://$AWS_BUCKET_NAME/ workdir --exclude "*" --include "*.jpg" --include "*.png"

      - name: Convert Images to WebP
        run: |
          pwd
        
          if [ -d workdir ] && ([ "$(ls -A workdir/*.jpg 2>/dev/null)" ] || [ "$(ls -A workdir/*.png 2>/dev/null)" ]); then
            for img in workdir/*.{jpg,png}; do
              [ -e "$img" ] || continue
              cwebp -resize 1024 0 "$img" -o workdir/$(basename "$img" | sed 's/\.[^.]*$//').webp
            done
          else
            echo "No image files found in workdir."
            exit 1
          fi

      - name: Upload Images to S3
        run: |
          aws s3 sync --endpoint-url https://$AWS_ENDPOINT_URL workdir s3://$AWS_BUCKET_NAME/ --exclude "*" --include "*.webp"

      - name: Format S3 URLs
        run: |
          aws s3 ls --recursive --endpoint-url https://$AWS_ENDPOINT_URL $AWS_BUCKET_NAME/ > s3_output.txt
          declare -A file_dict
          while read -r line; do
            if [[ $line =~ ([^[:space:]]+\.[^[:space:]]+)$ ]]; then
              filename="${BASH_REMATCH[1]}"
              extension="${filename##*.}"
              file_dict[$extension]+="${filename}\n"
            fi
          done < s3_output.txt
          for ext in "${!file_dict[@]}"; do
            printf "${file_dict[$ext]}"
          done
