name: Check S3 Bucket Contents

on:
  push:
    branches:
      - main

env:
  AWS_ENDPOINT_URL: s3.ap-northeast-1.wasabisys.com
  AWS_BUCKET_NAME: assets.potapoyo.com/photo/202408/20240817_worldhopping

jobs:
  list-s3-contents:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
      
    - name: Check AWS CLI
      run: |
        python -m pip install awscli
        aws --version

    - name: AWS Configure
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        aws configure list
        cat ~/.aws/credentials
        cat ~/.aws/config
        
    - name: List S3 bucket contents
      run: |
        aws s3 ls --recursive --endpoint-url https://$AWS_ENDPOINT_URL $AWS_BUCKET_NAME/
